name: publish Node.js Package	
on:	
  push:	
    branches:	
      - master	
jobs:	
  publish-npmjs:	
    runs-on: ubuntu-20.04	
    steps:	
      - uses: actions/checkout@v3	
      - uses: actions/setup-node@v3	
        with:	
         node-version: '16.x'	
         registry-url: 'https://registry.npmjs.org'	
      - uses: actions/setup-java@v3	
        with:	
          java-version: '11'	
          distribution: 'adopt'	
      - name: Update The Snapshot	
        id: get_version	
        run: echo "VERSION=$(echo ${GITHUB_REF##*/} | cut -d v -f 2)" >> $GITHUB_OUTPUT 
      - name: install ams 
        run: |
          git clone https://github.com/ant-media/ant-media-server-parent.git
          cd ant-media-server-parent/
          mvn clean install -Dgpg.skip=true
          cd ..
          git clone https://github.com/ant-media/Ant-Media-Server.git
          cd Ant-Media-Server
          mvn clean install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -Dgpg.skip=true
          cd Ant-Media-Server 
          sudo sh ./repackage_community.sh
          wget https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh && chmod 755 install_ant-media-server.sh
          sudo ./install_ant-media-server.sh -i Ant-Media-Server/target/ant*.zip
          
    
      
      - run: npm install --include=dev	
      - run: npm install --save-dev @babel/cli	
      - run: npm run compile	
      - run: wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_100.0.4896.127-1_amd64.deb
      - run: sudo dpkg -i google-chrome-stable_100.0.4896.127-1_amd64.deb
      - run: npm install ./src/test/js/
      - run: npm run test  --prefix ./src/test/js/
